config/routes.rb
WardMissionApplication::Application.routes.draw do
  
  get "visit_teaching/index"
  get "visit_teaching/new"
  get "visit_teaching/create"
  get "visit_teaching/show"
  get "visit_teaching/update"
  get "visit_teaching/destroy"
  get "sisters_in_need/index"
  get "sisters_in_need/new"
  get "sisters_in_need/create"
  get "sisters_in_need/show"
  get "sisters_in_need/update"
  get "sisters_in_need/destroy"
  resources :high_priest_group
  resources :relief_society
  resources :home_teaching
  resources :elders_quorum
  resources :ywym
  resources :primary
  resources :less_actives
  resources :converts
  resources :investigators
  
  get '/relief_society/index', to: 'relief_society#index'
  get '/high_priest_group/index', to: 'high_priest_group#index'
  get '/elders_quorum/index', to: 'elders_quorum#index'
  get '/ywym/index', to: 'ywym#index'
  get '/primary/index', to: 'primary#index'
  
  root to: "home#index"
  
end

app/models/convert.rb
class Convert < ActiveRecord::Base
end

app/models/home_teaching.rb
class HomeTeaching < ActiveRecord::Base
end

app/models/investigator.rb
class Investigator < ActiveRecord::Base
end

app/models/less_active.rb
class LessActive < ActiveRecord::Base
end

app/models/sisters_in_need.rb
class SistersInNeed < ActiveRecord::Base
end

app/models/visit_teaching.rb
class VisitTeaching < ActiveRecord::Base
end

app/controllers/converts_controller.rb
class ConvertsController < ApplicationController
  
  def index
    @converts = Convert.all
  end
  
  def new
  end
  
  def create
    @convert = Convert.new(convert_params)
    @convert.save
    redirect_to converts_path
  end
  
  def show
    @convert = Convert.find(params[:id])
  end
  
  private
  
  def convert_params
    params.require(:convert).permit(:first_name,
                                    :last_name,
                                    :address,
                                    :phone,
                                    :calling,
                                    :endowed,
                                    :ordained,
                                    :comments)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/investigators_controller.rb
class InvestigatorsController < ApplicationController
  
  def index
    @investigator = Investigator.all
  end
  
  def new
  end
  
  def create
    @investigator = Investigator.new(investigator_params)
    @investigator.save
    redirect_to investigators_path
  end
  
  def show
    @investigator = Investigator.find(params[:id])
  end
  
  private
  
  def investigator_params
    params.require(:investigator).permit(:first_name,
                                         :last_name,
                                         :address,
                                         :phone,
                                         :comments)
  end
  
end

app/controllers/primary_controller.rb
class PrimaryController < ApplicationController
  def index
  end
end

app/controllers/ywym_controller.rb
class YwymController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def footer
    link_to "Converts", converts_path
    link_to "Less Actives", less_actives_path
    link_to "Investigators", investigators_path
  end
  
end

app/helpers/converts_helper.rb
module ConvertsHelper
end

app/helpers/elders_quorum_helper.rb
module EldersQuorumHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/home_teaching_helper.rb
module HomeTeachingHelper
end

app/helpers/investigators_helper.rb
module InvestigatorsHelper
end

app/helpers/less_actives_helper.rb
module LessActivesHelper
end

app/helpers/primary_helper.rb
module PrimaryHelper
end

app/helpers/relief_society_helper.rb
module ReliefSocietyHelper
end

app/helpers/sisters_in_need_helper.rb
module SistersInNeedHelper
end

app/helpers/visit_teaching_helper.rb
module VisitTeachingHelper
end

app/helpers/ywym_helper.rb
module YwymHelper
end

app/views/investigators/index.html.erb
<h1>Boston 1st Ward :: Investigators</h1>

<%= link_to "Add New Investigator", new_investigator_path %>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
  </tr>
  
  <% @investigator.each do |c| %>
  
  <tr>
    <td><%= link_to "#{c.first_name} #{c.last_name}", c %></td>
    <td><%= c.address %></td>
    <td><%= c.phone %></td>
  </tr>
  
  <% end %>
</table>

<hr>

app/views/investigators/new.html.erb
<h1>Investigators</h1>

<p>Here is where the ward mission leader, ward missionaries, and ward
council can get an overview of priority investigators.</p>

<%= form_for :investigator, url: investigators_path do |f| %>
<div class="row">
  <div class="span6">
    <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
    </p>
    <p>
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </p>
    
    <p>
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </p>
    
    <p>
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </p>
  </div>
  <div class="span6">
    <p>
    <%= f.label :comments %><br>
    <%= f.text_area :comments, :class => "field span6", :rows => "10" %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  </div>
</div>
<% end %>

app/views/investigators/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @investigator.first_name + ' ' + @investigator.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @investigator.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @investigator.phone %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @investigator.comments %>
</p>

<%= link_to "Back to investigators", investigators_path %>