config/routes.rb
WardMissionApplication::Application.routes.draw do
  
  get "visit_teaching/index"
  get "visit_teaching/new"
  get "visit_teaching/create"
  get "visit_teaching/show"
  get "visit_teaching/update"
  get "visit_teaching/destroy"
  get "sisters_in_need/index"
  get "sisters_in_need/new"
  get "sisters_in_need/create"
  get "sisters_in_need/show"
  get "sisters_in_need/update"
  get "sisters_in_need/destroy"
  resources :high_priest_group
  resources :relief_society
  resources :home_teaching
  resources :elders_quorum
  resources :ywym
  resources :primary
  resources :less_actives
  resources :converts
  resources :investigators
  
  get '/relief_society/index', to: 'relief_society#index'
  get '/high_priest_group/index', to: 'high_priest_group#index'
  get '/elders_quorum/index', to: 'elders_quorum#index'
  get '/ywym/index', to: 'ywym#index'
  get '/primary/index', to: 'primary#index'
  
  root to: "home#index"
  
end

app/models/convert.rb
class Convert < ActiveRecord::Base
end

app/models/home_teaching.rb
class HomeTeaching < ActiveRecord::Base
end

app/models/investigator.rb
class Investigator < ActiveRecord::Base
end

app/models/less_active.rb
class LessActive < ActiveRecord::Base
end

app/models/sisters_in_need.rb
class SistersInNeed < ActiveRecord::Base
end

app/models/visit_teaching.rb
class VisitTeaching < ActiveRecord::Base
end

app/controllers/converts_controller.rb
class ConvertsController < ApplicationController
  
  def index
    @converts = Convert.all
  end
  
  def new
  end
  
  def create
    @convert = Convert.new(convert_params)
    @convert.save
    redirect_to converts_path
  end
  
  def show
    @convert = Convert.find(params[:id])
  end
  
  private
  
  def convert_params
    params.require(:convert).permit(:first_name,
                                    :last_name,
                                    :address,
                                    :phone,
                                    :calling,
                                    :endowed,
                                    :ordained,
                                    :comments)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/primary_controller.rb
class PrimaryController < ApplicationController
  def index
  end
end

app/controllers/sisters_in_need_controller.rb
class SistersInNeedController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/ywym_controller.rb
class YwymController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def footer
    link_to "Converts", converts_path
    link_to "Less Actives", less_actives_path
    link_to "Investigators", investigators_path
  end
  
end

app/helpers/converts_helper.rb
module ConvertsHelper
end

app/helpers/elders_quorum_helper.rb
module EldersQuorumHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/home_teaching_helper.rb
module HomeTeachingHelper
end

app/helpers/investigators_helper.rb
module InvestigatorsHelper
end

app/helpers/less_actives_helper.rb
module LessActivesHelper
end

app/helpers/primary_helper.rb
module PrimaryHelper
end

app/helpers/relief_society_helper.rb
module ReliefSocietyHelper
end

app/helpers/sisters_in_need_helper.rb
module SistersInNeedHelper
end

app/helpers/visit_teaching_helper.rb
module VisitTeachingHelper
end

app/helpers/ywym_helper.rb
module YwymHelper
end

app/views/sisters_in_need/create.html.erb
<h1>SistersInNeed#create</h1>
<p>Find me in app/views/sisters_in_need/create.html.erb</p>

app/views/sisters_in_need/destroy.html.erb
<h1>SistersInNeed#destroy</h1>
<p>Find me in app/views/sisters_in_need/destroy.html.erb</p>

app/views/sisters_in_need/index.html.erb
<h1>Relief Society :: Sisters in Need</h1>

<div class="row">
  <%= link_to "Relief Society Main", relief_society_index_path, :class => "span3 btn btn-lg" %>
  <%= link_to "Visit Teaching", visit_teaching_index_path, :class => "span4 btn btn-lg" %>
  <%= link_to "Sisters in Need", sisters_in_need_index_path, :class => "span4 btn btn-lg" %>
</div>

app/views/sisters_in_need/new.html.erb
<h1>SistersInNeed#new</h1>
<p>Find me in app/views/sisters_in_need/new.html.erb</p>

app/views/sisters_in_need/show.html.erb
<h1>SistersInNeed#show</h1>
<p>Find me in app/views/sisters_in_need/show.html.erb</p>

app/views/sisters_in_need/update.html.erb
<h1>SistersInNeed#update</h1>
<p>Find me in app/views/sisters_in_need/update.html.erb</p>